name: Collection tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    env:
      collection_directory: ansible.utils
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: "python ${{ matrix.python-version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install the current project
        run: |
          pip install -e .
      
      - name: Download ansible.utils
        run: |
          git clone https://github.com/ansible-collections/ansible.utils.git
      
      - name: Install collection requirements
        run: pip3 install -r requirements.txt -r test-requirements.txt 
        working-directory: ${{ env.collection_directory }}
      
      - name: Run unit tests
        run: pytest -v 
        working-directory: ${{ env.collection_directory }}