name: Collection tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        directory: ["/ansible.utils", "/collections/ansible_collections/ansible/utils"]
    name: "python ${{ matrix.python-version }} / ${{ matrix.directory }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install the current project
        run: |
          pip install -e .
      
      - name: Clone ansible.utils
        run: |
          git clone https://github.com/ansible-collections/ansible.utils.git ${{ matrix.directory }}
      
      - name: Install collection requirements
        run: pip3 install -r requirements.txt -r test-requirements.txt 
        working-directory: ${{ matrix.directory }}"
      
      - name: Run unit tests
        run: pytest -v 
        working-directory: ${{ matrix.directory }}"